## 第二章：处理文件、摄像头、用户图形界面

#### 1 读写图像文件

In [2]:
import numpy as np
import cv2 as cv
img = np.zeros((3,3), dtype=np.uint8)
img = cv.cvtColor(img, cv.COLOR_GRAY2BGR)

In [3]:
print(img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [4]:
img.shape

(3, 3, 3)

In [9]:
from matplotlib import pyplot as plt
%matplotlib inline
grayImage = cv.imread('MyPic.png', cv.IMREAD_GRAYSCALE)
cv.imwrite('MyPicGray.png', grayImage)
img = cv.imread('MyPic.png')
my_roi = img[0:100, 0:100]

#### 2 视频文件的读和写

In [12]:
cameraCapture = cv.VideoCapture(0)
fps = 30
size = (int(cameraCapture.get(cv.CAP_PROP_FRAME_WIDTH)),
       int(cameraCapture.get(cv.CAP_PROP_FRAME_HEIGHT)))
videoWriter = cv.VideoWriter('MyOutputVid.avi', 
                             cv.VideoWriter_fourcc('I', '4', '2', '0'),
                            fps, size)

success, frame = cameraCapture.read()
numFramesRemaining = 10 * fps - 1
while success and numFramesRemaining > 0:
    videoWriter.write(frame)
    success, frame = cameraCapture.read()
    numFramesRemaining -= 1
    
cameraCapture.release()

#### 3 在窗口显示摄像头帧

In [3]:
%reset -f
%matplotlib inline
import cv2 as cv
from matplotlib import pyplot as plt

clicked = False
def onMouse(event, x, y, flags, param):
    global clicked
    if event == cv.EVENT_LBUTTONUP:
        clicked = True

cameraCapture = cv.VideoCapture(0)
cv.namedWindow('MyWindow')
cv.setMouseCallback('MyWindow', onMouse)

print('Showing camera feed. Click window or press any key to stop.')
success, frame = cameraCapture.read()
while success and cv.waitKey(1) == -1 and not clicked:
    cv.imshow('MyWindow', frame)
    success, frame = cameraCapture.read()

cv.destroyWindow('MyWindow')
cameraCapture.release()

Showing camera feed. Click window or press any key to stop.
